spring.application.name=timebank

# Database
spring.datasource.url=jdbc:mysql://localhost:3306/timebank_db
spring.datasource.username=root
spring.datasource.password=sql@#2004
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# App
server.port=8080

# JWT
jwt.secret=timebankSecretKey2024SuperLongSecretKeyForJWTSigning
jwt.expiration=86400000